# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: butredocker
description: My optimized Fedora CoreOS image for running Docker and Fluxer on a Wyse 3040.
base-image: ghcr.io/ublue-os/ucore-minimal
image-version: lts

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - git
        - tailscale
    remove:
      packages:
        - cockpit
        - cockpit-bridge
        - cockpit-ostree
        - cockpit-podman
        - cockpit-system
        - qemu-guest-agent
        - open-vm-tools
        - podman-compose
        - zfs
        - pv

  - type: systemd
    system:
      enabled:
        - docker
        - tailscaled

  - type: signing
